// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcNcFCGWqfWSuffGkfkUKCaUzUwa_NQwQ',
    appId: '1:284059994649:web:7f1afa0f772efa8bad3888',
    messagingSenderId: '284059994649',
    projectId: 'fruits-hub-bccca',
    authDomain: 'fruits-hub-bccca.firebaseapp.com',
    storageBucket: 'fruits-hub-bccca.firebasestorage.app',
    measurementId: 'G-FQZ61CB7FD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkS2LF4eTVLS3ewcQDbI3GDbvWRUH-GkQ',
    appId: '1:284059994649:android:398a58d80a6d2007ad3888',
    messagingSenderId: '284059994649',
    projectId: 'fruits-hub-bccca',
    storageBucket: 'fruits-hub-bccca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnu51I1IJLRcgPeIrb89ZBBwV6Q9c_Klo',
    appId: '1:284059994649:ios:ce67405c5abd3649ad3888',
    messagingSenderId: '284059994649',
    projectId: 'fruits-hub-bccca',
    storageBucket: 'fruits-hub-bccca.firebasestorage.app',
    iosBundleId: 'com.example.fruitsECommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnu51I1IJLRcgPeIrb89ZBBwV6Q9c_Klo',
    appId: '1:284059994649:ios:ce67405c5abd3649ad3888',
    messagingSenderId: '284059994649',
    projectId: 'fruits-hub-bccca',
    storageBucket: 'fruits-hub-bccca.firebasestorage.app',
    iosBundleId: 'com.example.fruitsECommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcNcFCGWqfWSuffGkfkUKCaUzUwa_NQwQ',
    appId: '1:284059994649:web:4f45ee30dc073c65ad3888',
    messagingSenderId: '284059994649',
    projectId: 'fruits-hub-bccca',
    authDomain: 'fruits-hub-bccca.firebaseapp.com',
    storageBucket: 'fruits-hub-bccca.firebasestorage.app',
    measurementId: 'G-Y6V3B9TGC5',
  );
}
